### ISSUE TITLE
Support for Moga Pocket possible?

### ISSUE THREAD

**Issue by CoconutzX** [Zel-os/MogaSerial#11] opened 2017-02-15 07:05 UTC
I can't connect my Moga Pocket becouse it doesn't have an A Mode. Is there a possibility to use MogaSerial for this particular model?

![image](https://cloud.githubusercontent.com/assets/21298293/22963832/0064a8ba-f334-11e6-904e-fef0655f291f.png)

Thanks

**Comment by jpgbac** [comment] 2017-02-28 03:20
I 2nd this question, the moga pocket would be great to use with my Chromebook/crouton linux as well.

**Comment by Zel-os** [comment] 2017-02-28 21:52
I seem to get asked this a lot, which means I ought to make it more clear in the readme file.  Anyway!

The Moga Pocket is not officially supported, but with the following settings it will work:

- Set input driver to `vJoy`
- Set trigger mode to `Button`

Duplicate of issue https://github.com/Zel-os/MogaSerial/issues/4

**Closed as completed by Zel-os** 2017-02-28 21:52 UTC
Labels: duplicate
